<?php
/**
 * @file
 * APubSub module file.
 */

/**
 * Default backend class.
 */
const APB_SERVICE = 'apb.backend';

/**
 * Menu helper, please do not use directly.
 *
 * @return \MakinaCorpus\APubSub\BackendInterface
 */
function apb_backend_load($name) {
  \Drupal::service(APB_SERVICE);
}

/**
 * Implements hook_cron().
 */
function apb_cron() {
  try {
    apb_backend_load(APB_SERVICE)->garbageCollection();
  } catch (Exception $e) {
    // We cannot afford cron failure here, outdated data must be wiped
    // out no matter the cost, just leave some comprehensive exception
    // logging in case of any error
    watchdog_exception('apb', $e, "Backend could not be instanciated", NULL, WATCHDOG_ERROR);
  }
}
