<?php
/**
 * @file
 * APubSub module file.
 */

/**
 * Menu helper, please do not use directly.
 *
 * @return \MakinaCorpus\APubSub\BackendInterface
 */
function apb_backend_load() {
  return \Drupal::service('apb.backend');
}

/**
 * Implements hook_cron().
 */
function apb_cron() {
  try {
    apb_backend_load()->garbageCollection();
  } catch (Exception $e) {
    // We cannot afford cron failure here, outdated data must be wiped
    // out no matter the cost, just leave some comprehensive exception
    // logging in case of any error
    watchdog_exception('apb', $e, "Backend could not be instanciated", NULL, WATCHDOG_ERROR);
  }
}
